HW_10/HW_10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

HW_10/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("author/<str:a_fullname>/", views.author_info, name="author_info"),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    ]

HW_10/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .forms import LoginForm
from .views import RegisterView

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name="users/login.html", authentication_form=LoginForm,
                                     redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"),
]

HW_10/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_loc = models.CharField(max_length=150)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Quotes(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

HW_10/users/models.py
from django.db import models

# Create your models here.

HW_10/quotes/forms.py
from django import forms
from .models import Author, Quotes



class AddAuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_loc', 'desc']
        labels = {
            "fullname": "Authors Full Name",
            "born_date": "Date of birth",
            "born_loc": "Birth location",
            "desc": "Description",
        }


class AddQuoteForm(forms.ModelForm):
    custom_author = forms.CharField(label='Custom Author', required=False)
    existing_author = forms.ModelChoiceField(queryset=Author.objects.all(),
                                             label='Existing Author', required=False)

    class Meta:
        model = Quotes
        fields = ['quote']
        labels = {
            'quote': 'Quote',
        }

    def save(self, commit=True):
        quote = super().save(commit=False)

        if commit:
            quote.save()

        custom_author = self.cleaned_data['custom_author']
        existing_author = self.cleaned_data['existing_author']
        if custom_author:
            author, created = Author.objects.get_or_create(fullname=custom_author)
            quote.author = author
        elif existing_author:
            quote.author = existing_author

        if commit:
            quote.save()
        return quote

HW_10/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, required=True, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=150, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]\



class LoginForm(AuthenticationForm):
    username = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=20, min_length=8, required=True,
                           widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ["username", "password"]

HW_10/quotes/views.py
import json
from collections import Counter

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import AddAuthorForm, AddQuoteForm
from .models import Quotes, Author


def main(request):
    quotes = Quotes.objects.all().order_by("-created_at")

    return render(request, "quotes/index.html",
                  context={"quotes": quotes})


def author_info(request, a_fullname):
    author_inf = Author.objects.get(fullname=a_fullname)
    quotes_by_author = Quotes.objects.filter(author__fullname=a_fullname)
    return render(request, "quotes/author_quotes.html", context={"quotes": quotes_by_author, "author_info": author_inf})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AddAuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = AddAuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


@login_required
def add_quote(request):
    authors = Author.objects.all()

    if request.method == 'POST':
        form = AddQuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = AddQuoteForm()

    context = {'form': form, "author": authors}
    return render(request, 'quotes/add_quote.html', context)

HW_10/users/views.py
from http.client import HTTPResponse

from django.shortcuts import render, redirect
from django.views import View

from .forms import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/register.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes:root")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form})

HW_10/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h3>Add Author</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
{% endblock %}

HW_10/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}
  <h3>Add Quote</h3>
  <form method="post" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Quote</button>
  </form>
{% endblock %}

HW_10/quotes/templates/quotes/author_quotes.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="author-container">
    <div class="author-details">
        <h1 class="authorName">
            <span itemprop="name">{{ author_info.fullname }}</span>
        </h1>
        <div class="data-row">
            <div class="dataTitle">Born:</div>
            <div class="dataItem">{{ author_info.born_loc }}</div>
        </div>
        <div class="data-row">
            <div class="dataTitle">Born date:</div>
            <div class="dataItem">{{ author_info.born_date }}</div>
        </div>
        <div class="data-row">
            <div class="dataTitle">Description:</div>
            <div class="dataItem">{{ author_info.desc }}</div>
        </div>
    </div>

    <div class="quote-container">
        <h3>Quotes by {{ author_info.fullname }}</h3>
        <div class="row">
            <div class="col-md-8">
                {% for quote in quotes %}
                <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                    <span class="text" itemprop="text">{{ quote.quote }}</span>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

HW_10/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'qoutes\style.css' %}">
    <title>HW_10</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4 d-flex justify-content-end">
            <p>
                {% if user.is_authenticated %}
            <div class="greeting">
                <a>
                    Hello, <span class="text-primary">{{ user.username }}</span>!
                </a>
            </div>
            <div class="d-inline-block align-middle">
                <a href="{% url 'users:logout' %}" class="btn btn-primary btn-sm" style="margin-right: 10px;">Logout</a>
            </div>
            {% else %}
            <div class="d-inline-block align-middle">
                <a href="{% url 'users:register' %}" class="btn btn-primary btn-sm"
                   style="margin-right: 8px;">Register</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary btn-sm">Login</a>
            </div>
            {% endif %}
            </p>
        </div>
    </div>

    {% block content %} {% endblock %}

</div>
</body>
</html>

HW_10/quotes/templates/quotes/base_author.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>HW_10</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
    </div>

    {% block content %} {% endblock %}

</div>
</body>
</html>

HW_10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% if user.is_authenticated %}
        <a href="{% url 'quotes:add_author' %}" class="btn btn-primary mb-3 md-5">Add Author</a>

        <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary mb-3 md-5">Add Qoute</a>
        {% endif %}

        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <div class="author-info">
                <a href="{% url 'quotes:author_info' quote.author.fullname %}">
                    <span class="author-name">{{ quote.author.fullname }}</span>
                </a>
            </div>
        {% endfor %}        
    </div>


</div>
{% endblock %}

HW_10/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}

<h3>Login</h3>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}}" role="alert">
  {{ message }}
</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
</div>
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sing In</button>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>
{% endblock %}

HW_10/users/templates/users/logout.html
{% extends "quotes/base.html" %}
{% block content %}
<h1>Good Bye!</h1>
{% endblock %}

HW_10/users/templates/users/register.html
{% extends 'quotes/base.html' %}

{% block content %}

<h3>Register</h3>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">First Name</label>
            {{form.first_name}}
        </div>
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Last Name</label>
            {{form.last_name}}
        </div>
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Enter password again</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sing Up</button>
</form>
{% endblock %}